### ISSUE TITLE
Windows Visual Studio 2019 Build problems

### ISSUE THREAD

**Issue by The5-1** [polymonster/pmtech#51]
It seems pmbuild should be able to find VS2019 if installed.
I do not have it on C:\, so that may be the issue.
After manually specifying the path to the vcvarsall.bat I get an error.

```
PS F:\Dev\GameDev\pmtech\examples> ..\pmbuild.cmd win32-gl

F:\Dev\GameDev\pmtech\examples>py -3 F:\Dev\GameDev\pmtech\\\third_party\\pmbuild\\scripts\\pmbuild.py win32-gl
--------------------------------------------------------------------------------
pmbuild (v4) -------------------------------------------------------------------
--------------------------------------------------------------------------------
Cannot find 'vcvarsall.bat'
Please enter the full path to the msvc installation directory containing vcvarsall.bat
"F:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Auxiliary\Build\vcvarsall.bat"
--------------------------------------------------------------------------------
premake ------------------------------------------------------------------------
--------------------------------------------------------------------------------
Premake: loaded module android-studio
platform: win32
renderer: opengl
pmtech dir: ../
sdk version: 10.0.18362.0
Error: no such action 'vsInstaller'
[error] processing file
PS F:\Dev\GameDev\pmtech\examples>
```

**Comment by polymonster** [comment]
Looks like `%{vs_latest}` variable used in `config.jsn` is finding `vsInstaller` as the latest vs version and not vs2019... for the time being you could replace `%{vs_latest}` in the config with "vs2019".

The issue is caused by multiple `Program Files (x86)\Microsoft Visual Studio` directories on different drives... I will try and update pmbuild to be a bit more resilient to this.

**Comment by polymonster** [comment]
This should now be fixed, the vs version can be determined from the users set vcvarsall_dir and pmbuild will only look for valid vs installs

**Comment by ompadu** [comment]
It seems it's still happening for me, but the fix worked (_replace %{vs_latest} in the config with "vs2019"_).
